/*
 * Continuously generates page faults at a frequency that oscillates between
 * min_frequency and max_frequency with the given period. The program can be
 * used to test the eBPF program that counts page faults.
 *
 * Note that the number of page faults generated by this program is not exact.
 * The actual number of page faults generated may be a bit different than the
 * specified number due to the way the kernel handles page faults.
 *
 * Usage: ./page_fault_gen <min_frequency> <max_frequency> <period_ms>
 * 
 * DO NOT EDIT THIS CODE!
*/
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <stdbool.h>
#include <sys/mman.h>

#define PAGE_SIZE 4096  // Usually 4KB
#define INTERVAL_NS 1000000L // 1 ms in nanoseconds

int warning_printed = 0;

void generate_page_faults(size_t num_pages) {
    // Allocate memory (mmap ensures it's demand-paged)
    char *buffer = mmap(NULL, num_pages * PAGE_SIZE, PROT_READ | PROT_WRITE,
                        MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    
    if (buffer == MAP_FAILED) {
        perror("mmap failed");
        exit(EXIT_FAILURE);
    }

    // Touch each page to trigger a page fault
    for (size_t i = 0; i < num_pages; i++) {
        buffer[i * PAGE_SIZE] = 1;  // Write to each page
    }

    // Free the memory
    munmap(buffer, num_pages * PAGE_SIZE);
}

// Returns the current time as a timespec
static struct timespec now() {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return t;
}

// Sleeps until the target time. Does nothing if target is already in the past.
static void sleep_until(struct timespec target) {
    struct timespec current = now();

    // Compute remaining = target - current
    long remaining_ns = (target.tv_sec - current.tv_sec) * 1000000000L
                        + (target.tv_nsec - current.tv_nsec);

    if (remaining_ns <= 0) {
        if ((!warning_printed) && remaining_ns < -1000000000L /* 1 second */) {
            warning_printed = 1;
            fprintf(stderr, "Warning: You are way behind schedule, your machine can't keep up with the target frequency. Consider reducing max_frequency.\n");
        }
        return; // Already past the target, no sleep needed
    }

    struct timespec remaining = {
        .tv_sec  = remaining_ns / 1000000000L,
        .tv_nsec = remaining_ns % 1000000000L
    };
    nanosleep(&remaining, NULL);
}

// Adds interval_ns nanoseconds to a timespec
static struct timespec add_ns(struct timespec t, long ns) {
    t.tv_nsec += ns;
    t.tv_sec  += t.tv_nsec / 1000000000L;
    t.tv_nsec  = t.tv_nsec % 1000000000L;
    return t;
}

int main(int argc, char *argv[]) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <min_frequency> <max_frequency> <period_ms>\n", argv[0]);
        return EXIT_FAILURE;
    }
    
    size_t min_frequency = strtoul(argv[1], NULL, 10);
    size_t max_frequency = strtoul(argv[2], NULL, 10);
    size_t period_ms = strtoul(argv[3], NULL, 10);

    double num_pages = (max_frequency + min_frequency) / 2.0; // Start at the average frequency
    bool increasing = true; // Flag to determine if we are increasing or decreasing the frequency

    double delta = (max_frequency - min_frequency) / ((period_ms/2) / 1.0); // Calculate the change in frequency per ms
    if ((size_t) delta > (max_frequency - min_frequency)) {
        delta = (double) (max_frequency - min_frequency); // Ensure we don't overshoot the max frequency
    }

    if (delta == 0) {
        printf("Continuously generating page faults at a constant frequency of %zu page faults/ms\n", (size_t) num_pages);
    }

    size_t total_pages_faulted = 0;
    struct timespec next_tick = now(); // The deadline for the next iteration

    while (total_pages_faulted < max_frequency * 1000 * 10) { // Run for a while (e.g., 10 seconds at max frequency)

        // Schedule the next tick before doing any work, so processing time is
        // accounted for and the sleep at the end is shortened accordingly.
        next_tick = add_ns(next_tick, INTERVAL_NS);

        generate_page_faults((size_t) num_pages);
        total_pages_faulted += (size_t) num_pages;

        // Sleep only for the time remaining until the next tick
        sleep_until(next_tick);

        if (delta == 0) {
            continue;
        }

        if (increasing) {
            num_pages += delta; // Increase the number of pages to generate more page faults
            if ((size_t) num_pages >= max_frequency) {
                increasing = false; // Start decreasing after reaching max frequency
                printf("Reached max frequency: %zu page faults/ms\n", (size_t) num_pages);
            }
        } else {
            if (delta > num_pages) {
                num_pages = 0.0;
            }
            else {
                num_pages -= delta; // Decrease the number of pages to generate fewer page faults
            }
            if ((size_t) num_pages <= min_frequency) {
                increasing = true; // Start increasing after reaching min frequency
                printf("Reached min frequency: %zu page faults/ms\n", (size_t) num_pages);
            }
        }
    }

    return EXIT_SUCCESS;
}
